[package]
name = "mr-comment"
version = "0.1.0"
edition = "2021"
description = "CLI tool to generate GitLab MR comments from git diffs using AI (OpenAI or Claude)"
authors = ["Robert Kozak"]
license = "MIT"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
reqwest = { version = "0.11.24", features = ["json", "blocking"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
anyhow = "1.0.80"
dirs = "5.0.1"
tokio = { version = "1.36.0", features = ["full"] }
